/**
 * The Cocktail DataBase
 * An open API to handle cocktail recepies. Drink thumbnails and images Add /preview to the end of the cocktail image URL. (100x100) Ingredients www.thecocktaildb.com/images/ingredients/gin-Small.png (100x100) www.thecocktaildb.com/images/ingredients/gin-Medium.png (350x350) www.thecocktaildb.com/images/ingredients/gin.png (700x700)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { CocktailResponse } from '../model/cocktailResponse';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ListService {

    protected basePath = 'www.thecocktaildb.com/api/json/v1/1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * List any of categories, glasses, ingredients or alcoholic filters
     * @param c All categories
     * @param g All glasses
     * @param i All ingredients
     * @param a All alcoholic filters
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPhpGet(c?: string, g?: string, i?: string, a?: string, observe?: 'body', reportProgress?: boolean): Observable<CocktailResponse>;
    public listPhpGet(c?: string, g?: string, i?: string, a?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CocktailResponse>>;
    public listPhpGet(c?: string, g?: string, i?: string, a?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CocktailResponse>>;
    public listPhpGet(c?: string, g?: string, i?: string, a?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {





        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (c !== undefined && c !== null) {
            queryParameters = queryParameters.set('c', <any>c);
        }
        if (g !== undefined && g !== null) {
            queryParameters = queryParameters.set('g', <any>g);
        }
        if (i !== undefined && i !== null) {
            queryParameters = queryParameters.set('i', <any>i);
        }
        if (a !== undefined && a !== null) {
            queryParameters = queryParameters.set('a', <any>a);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<CocktailResponse>('get',`${this.basePath}/list.php`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
